

#BACKLIGHT_ENABLE = yes
#BACKLIGHT_DRIVER = pwm
WS2812_DRIVER = vendor
RGBLIGHT_ENABLE = yes
BACKLIGHT_ENABLE = yes
BACKLIGHT_DRIVER = pwm
#HAL_USE_PWM = true
#RP_PWM_USE_PWM4 = true
CONSOLE_ENABLE = yes